In [ ]:
import pandas as pd
import re
import numpy as np

In [ ]:
#install tensorflow 2.8
!pip install tensorflow==2.8.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#ambil link project dataset
url = 'https://raw.githubusercontent.com/RashidMaulana/Anticede/main/Machine%20Learning/testing/data_testing/data%20-%20datatest%20(3).csv'
dataset = pd.read_csv(url)

# Change text to lowercase
def proses_data(text):
    newText = text.lower()
    return newText
#ini case kalau semua mau ngerun semua data Komputerku kentang maka ngefreeze)
# dataset['comment_text'].apply(lambda x: print(x))
#ini case kalau semua mau ngerun 5 data pertama
testData = dataset['original_text']
testData = testData.apply(lambda x: proses_data(x))


#menghilangkan link dan tag html
import re
def link_remover(text):
    url_regex = re.compile(r'(http|ftp|https)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?')
    return url_regex.sub('', text)
testData = testData.apply(lambda x: link_remover(x))

#menghilangkan kalimat bersama tag
import re
def tag_remover(text):
    tag_regex = re.compile(r'<[^>]+>')
    return tag_regex.sub('', text)
testData = testData.apply(lambda x: tag_remover(x))

# menghilangkan tanda baca dan karakter spesial
import re
def karakter_spesial(text):
    newText = re.sub('[^a-zA-Z0-9\s]', '', text)
    return newText
testData = testData.apply(lambda x: karakter_spesial(x))

# menghilangkan spasi berlebihan
def Spasi_berlebihan(text):  
    newText = re.sub('\s', ' ', text)
    return newText
testData = testData.apply(lambda x: Spasi_berlebihan(x))

#menghilangkan angka yang tidak perlu
def angka_berlebihan(text):
    newText = re.sub('[0-9]', '', text)
    return newText
testData = testData.apply(lambda x: angka_berlebihan(x))
print(testData)

0        bukan cuma spanduk prof video orasi mereka bu...
1       gua sange gatel yah tetek memek y di ranjang t...
2       pertama kali denger lagunya enak bangitu in da...
3       astajim ini pasti yang kasih penghargaan ke ib...
4       kalo keberagamannya ada tapi ga dianggep banya...
                              ...                        
4995                               bad mood banget sumpah
4996    circle sekolah islam malang is weird af they b...
4997    megawati kalau aku sudah tidak ada piye yo ban...
4998    dari sini rakyat bisa menilai betapa kerdilnya...
4999    tenggelamkan  ini dalang adanya politik sara y...
Name: original_text, Length: 5000, dtype: object


In [ ]:
#pengecekan Data
dataset['pornografi'].value_counts()
#dataset['sara'].value_counts()
#dataset['radikalisme'].value_counts()
#dataset['pencemaran_nama_baik'].value_counts()
#dataset['original_text'].count()

0.0    4565
1.0     434
Name: pornografi, dtype: int64

In [ ]:
#melatih data train dengan tensorflow
url_train_data = 'https://raw.githubusercontent.com/RashidMaulana/Anticede/main/Machine%20Learning/testing/data_testing/data%20-%20datatrain.csv'
train_data = pd.read_csv(url_train_data)

# Change text to lowercase
def proses_data(text):
    newText = text.lower()
    return newText
traindata = train_data['original_text']
traindata = traindata.apply(lambda x: proses_data(x))

#menghilangkan link dan tag html
def link_remover(text):
    url_regex = re.compile(r'(http|ftp|https)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?')
    return url_regex.sub('', text)
traindata = traindata.apply(lambda x: link_remover(x))

#menghilangkan kalimat bersama @name
def name_remover(text):
    name_regex = re.compile(r'@[\w_-]+')
    return name_regex.sub(' ', text)
traindata = traindata.apply(lambda x: name_remover(x))

#menghilangkan tanda baca dan karakter spesial
def karakter_spesial(text):
    newText = re.sub('[^a-zA-Z0-9\s]', ' ', text)
    return newText
traindata = traindata.apply(lambda x: karakter_spesial(x))

#menghilang angka yang nempel dengan kalimat
def angka_berlebihan(text):
    newText = re.sub('[0-9]', '', text)
    return newText
traindata = traindata.apply(lambda x: angka_berlebihan(x))

#menghilangkan spasi berlebihan
def Spasi_berlebihan(text):  
    newText = re.sub('\s+', '', text)
    newText = re.sub('^\s+', '', text)
    return newText
traindata = traindata.apply(lambda x: Spasi_berlebihan(x))
print(traindata)

0      ya allah jika mereka menempuh cara curang untu...
1      yang terasa itu radikalisme semakin kuat isis ...
2      iya kesel udah kalah debat gua diblok lagi kel...
3      fans boleh dek tapi jangan sampe ikut merubah ...
4      ga usah tunggu lama dadamu yang disumpel silik...
                             ...                        
995                               ya angkot lebih goblog
996    njirr pahanya kok berlemak nabati gitu sih mas...
997    tidak ada  formula  a hingga z yang bisa mengh...
998    di usia yang masih sangat muda   tahun  hati d...
999            bangsat nih orang kerjanya serabutan kah 
Name: original_text, Length: 1000, dtype: object


In [ ]:
#pengecekan Data
train_data['pornografi'].value_counts()
#train_data['sara'].value_counts()
#train_data['radikalisme'].value_counts()
#train_data['pencemaran_nama_baik'].value_counts()
#train_data['original_text'].count()

0.0    894
1.0    105
Name: pornografi, dtype: int64

In [ ]:
#import tokenizer
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=10000, oov_token="<OOV>")
tokenizer.fit_on_texts(testData)
tokenizer.word_index



{'<OOV>': 1,
 'yang': 2,
 'dan': 3,
 'di': 4,
 'itu': 5,
 'ini': 6,
 'orang': 7,
 'ada': 8,
 'dari': 9,
 'dengan': 10,
 'ya': 11,
 'jadi': 12,
 'presiden': 13,
 'tapi': 14,
 'juga': 15,
 'ga': 16,
 'gak': 17,
 'bisa': 18,
 'aja': 19,
 'untuk': 20,
 'tidak': 21,
 'sama': 22,
 'saya': 23,
 'jokowi': 24,
 'ke': 25,
 'gue': 26,
 'kalo': 27,
 'nya': 28,
 'mau': 29,
 'agama': 30,
 'lagi': 31,
 'apa': 32,
 'dia': 33,
 'aku': 34,
 'lu': 35,
 'indonesia': 36,
 'islam': 37,
 'kita': 38,
 'karena': 39,
 'kalau': 40,
 'mereka': 41,
 'sudah': 42,
 'jangan': 43,
 'bukan': 44,
 'udah': 45,
 'dalam': 46,
 'akan': 47,
 'lain': 48,
 'lo': 49,
 'lebih': 50,
 'pada': 51,
 'kafir': 52,
 'banyak': 53,
 'semua': 54,
 'asing': 55,
 'pak': 56,
 'masih': 57,
 'kan': 58,
 'kok': 59,
 'cina': 60,
 'si': 61,
 'adalah': 62,
 'atau': 63,
 'cebong': 64,
 'tak': 65,
 'anak': 66,
 'buat': 67,
 'cuma': 68,
 'punya': 69,
 'negara': 70,
 'gitu': 71,
 'sekarang': 72,
 'lah': 73,
 'seperti': 74,
 'ganti': 75,
 'baru': 76,
 

In [ ]:
#change tokenizer to sequence integer
testData_sequences = tokenizer.texts_to_sequences(testData)
traindata_sequences = tokenizer.texts_to_sequences(traindata)
print(testData_sequences)
print(traindata_sequences)


[[44, 68, 1497, 758, 221, 3507, 41, 1259, 41, 3, 48, 48, 5, 42, 160, 216, 23, 795, 22, 77, 2, 57, 201, 45, 216, 8, 1369, 9, 796, 2, 313, 1260, 240, 75, 259, 57, 1644, 17, 8, 73, 29, 1260, 240, 19, 483, 2070, 240], [89, 347, 6855, 417, 759, 98, 2071, 4, 2392, 271, 727, 4, 1010, 381, 2072, 1011, 1261, 95, 115, 2073, 333, 95, 115, 889, 16, 417, 1645, 890], [394, 157, 1012, 1646, 277, 6856, 405, 3, 217, 6857, 6858, 191, 155, 2835, 89, 1646, 39, 277, 6859, 159, 155, 51, 2835, 1646, 1647, 4549], [2393, 6, 128, 2, 214, 4550, 25, 348, 2394, 62, 146, 55, 6860, 3, 6861, 3508, 6862], [27, 6863, 8, 14, 16, 6864, 53, 14, 6865, 8, 14, 6866, 202, 132, 19, 159, 3509, 31, 891], [57, 6867, 553, 6868, 6869, 4551, 2, 76], [2836, 66, 6, 1498, 797, 427, 143, 197, 158, 518, 6870, 6871, 4552, 85, 2395, 760, 2074], [6872, 454, 4553, 2075, 953, 122, 647, 39, 4554, 1853, 12, 2837, 152, 33, 45, 1499, 95], [173, 6873, 687, 798, 954, 369, 2838, 595, 2, 438, 728, 2396, 3, 2396, 298, 2076, 149, 834, 892, 6874, 168, 1

In [ ]:
#numpy array
testData_sequences = np.array(testData_sequences)
traindata_sequences = np.array(traindata_sequences)
print(testData_sequences)
print(traindata_sequences)

[list([44, 68, 1497, 758, 221, 3507, 41, 1259, 41, 3, 48, 48, 5, 42, 160, 216, 23, 795, 22, 77, 2, 57, 201, 45, 216, 8, 1369, 9, 796, 2, 313, 1260, 240, 75, 259, 57, 1644, 17, 8, 73, 29, 1260, 240, 19, 483, 2070, 240])
 list([89, 347, 6855, 417, 759, 98, 2071, 4, 2392, 271, 727, 4, 1010, 381, 2072, 1011, 1261, 95, 115, 2073, 333, 95, 115, 889, 16, 417, 1645, 890])
 list([394, 157, 1012, 1646, 277, 6856, 405, 3, 217, 6857, 6858, 191, 155, 2835, 89, 1646, 39, 277, 6859, 159, 155, 51, 2835, 1646, 1647, 4549])
 ... list([1961, 40, 34, 42, 21, 8, 2770, 970, 179, 6, 116, 110, 915])
 list([9, 300, 77, 18, 1943, 1877, 1, 195, 7, 6, 3, 216, 21, 828, 1525, 179, 6])
 list([2337, 6, 3212, 785, 182, 792, 2, 450, 1, 66, 179, 452, 4309, 492, 173])]
[list([11, 84, 154, 41, 8896, 225, 1803, 20, 1717, 61, 280, 30, 2019, 8897, 1901, 5169, 20, 4507])
 list([2, 1804, 5, 3247, 323, 823, 1273, 1, 42, 8899, 8900, 5508, 8901, 1863, 240, 4, 436, 637, 796, 566])
 list([196, 868, 45, 393, 372, 89, 4983, 31, 902, 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
#make a model word filter
from keras.preprocessing.sequence import pad_sequences
testData_sequences = pad_sequences(testData_sequences, padding='post', truncating='post', maxlen=100)
traindata_sequences = pad_sequences(traindata_sequences, padding='post', truncating='post', maxlen=100)
print(testData_sequences)
print("-----------------")
print(traindata_sequences)




[[  44   68 1497 ...    0    0    0]
 [  89  347 6855 ...    0    0    0]
 [ 394  157 1012 ...    0    0    0]
 ...
 [1961   40   34 ...    0    0    0]
 [   9  300   77 ...    0    0    0]
 [2337    6 3212 ...    0    0    0]]
-----------------
[[  11   84  154 ...    0    0    0]
 [   2 1804    5 ...    0    0    0]
 [ 196  868   45 ...    0    0    0]
 ...
 [  21    8    1 ...    0    0    0]
 [   4 2638    2 ...    0    0    0]
 [ 427  126    7 ...    0    0    0]]


In [30]:
#build model
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM, Dropout
model = Sequential()
model.add(Embedding(10000, 100, input_length=100))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(4, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 100, 100)          1000000   
                                                                 
 lstm_2 (LSTM)               (None, 100)               80400     
                                                                 
 dense_2 (Dense)             (None, 4)                 404       
                                                                 
Total params: 1,080,804
Trainable params: 1,080,804
Non-trainable params: 0
_________________________________________________________________


In [31]:
#train model
model.fit(traindata_sequences, train_data['sara'], epochs=10, batch_size=16)

Epoch 1/10
63/63 [==============================] - 27s 265ms/step - loss: 0.5445 - accuracy: 0.8350
Epoch 2/10
63/63 [==============================] - 12s 193ms/step - loss: 0.4362 - accuracy: 0.8480
Epoch 3/10
63/63 [==============================] - 12s 192ms/step - loss: 0.4320 - accuracy: 0.8480
Epoch 4/10
63/63 [==============================] - 13s 204ms/step - loss: 0.4295 - accuracy: 0.8480
Epoch 5/10
63/63 [==============================] - 12s 193ms/step - loss: 0.4306 - accuracy: 0.8480
Epoch 6/10
63/63 [==============================] - 12s 192ms/step - loss: 0.4254 - accuracy: 0.8480
Epoch 7/10
63/63 [==============================] - 12s 195ms/step - loss: 0.4316 - accuracy: 0.8480
Epoch 8/10
63/63 [==============================] - 13s 200ms/step - loss: 0.4286 - accuracy: 0.8480
Epoch 9/10
63/63 [==============================] - 12s 195ms/step - loss: 0.4371 - accuracy: 0.8480
Epoch 10/10
63/63 [==============================] - 12s 195ms/step - loss: 0.4332 - accura

In [32]:
# save model in h5 format
model.save('anticede_model.h5')

In [34]:
import os
import tensorflow as tf

model_version = "1"
model_save = "anticede"
model_path = os.path.join(model_save, model_version)
tf.saved_model.save(model, model_path)

INFO:tensorflow:Assets written to: anticede/1/assets


In [35]:
!zip -r log.zip log /content/anticede

	zip warning: name not matched: log
  adding: content/anticede/ (stored 0%)
  adding: content/anticede/1/ (stored 0%)
  adding: content/anticede/1/assets/ (stored 0%)
  adding: content/anticede/1/saved_model.pb (deflated 90%)
  adding: content/anticede/1/variables/ (stored 0%)
  adding: content/anticede/1/variables/variables.index (deflated 61%)
  adding: content/anticede/1/variables/variables.data-00000-of-00001 (deflated 37%)
